import { defineRecipe } from "@pandacss/dev";

/**
 * Park UI utility recipes the `@park-ui/panda-preset` does NOT bundle.
 *
 * The park-ui CLI drops these under `styled-system/recipes/*.ts`, but that dir
 * is gitignored + regenerated by `deno task prepare` — so on a fresh checkout
 * they vanish and any component importing them (Button → Group, Loader →
 * AbsoluteCenter) fails to build. Register them here (committed) and Panda
 * codegen emits the matching `styled-system/recipes/*.mjs`.
 *
 * Definitions are verbatim from the CLI output — keep in sync if the CLI
 * regenerates them.
 */

export const group = defineRecipe({
  className: "group",
  base: {
    display: "inline-flex",
    position: "relative",
    gap: "2",
    "& > *": {
      _focusVisible: {
        zIndex: 1,
      },
    },
  },
  defaultVariants: {
    orientation: "horizontal",
  },
  variants: {
    orientation: {
      horizontal: {
        flexDirection: "row",
      },
      vertical: {
        flexDirection: "column",
      },
    },
    attached: {
      true: {
        gap: "0",
      },
    },
    grow: {
      true: {
        display: "flex",
        "& > *": {
          flex: 1,
        },
      },
    },
  },
  compoundVariants: [
    {
      orientation: "horizontal",
      attached: true,
      css: {
        "& > *:first-child": {
          borderEndRadius: "0",
          marginEnd: "-1px",
        },
        "& > *:last-child": {
          borderStartRadius: "0",
        },
        "& > *:not(:first-child):not(:last-child)": {
          borderRadius: "0",
          marginEnd: "-1px",
        },
      },
    },
    {
      orientation: "vertical",
      attached: true,
      css: {
        "& > *:first-child": {
          borderBottomRadius: "0",
          marginBottom: "-1px",
        },
        "& > *:last-child": {
          borderTopRadius: "0",
        },
        "& > *:not(:first-child):not(:last-child)": {
          borderRadius: "0",
          marginBottom: "-1px",
        },
      },
    },
  ],
});

export const absoluteCenter = defineRecipe({
  className: "absolute-center",
  base: {
    position: "absolute",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  defaultVariants: {
    axis: "both",
  },
  variants: {
    axis: {
      horizontal: {
        insetStart: "50%",
        translate: "-50%",
        _rtl: {
          translate: "50%",
        },
      },
      vertical: {
        top: "50%",
        translate: "0 -50%",
      },
      both: {
        insetStart: "50%",
        top: "50%",
        translate: "-50% -50%",
        _rtl: {
          translate: "50% -50%",
        },
      },
    },
  },
});
